export const referencePages = [
  {
    slug: 'project-overview',
    title: '项目总览',
    group: '工作区与项目',
    href: '/docs/interface-guides/project-overview',
    image: '/api/reference-assets/project-overview.png',
    summary: '进入项目后的统一入口页，用于连接 Use 面与 Govern 面。',
    label: 'Project Surface',
    note: '统一进入聊天、任务、文件与治理。',
    objectPosition: '52% 22%',
    scale: 1.24,
    viewportClassName: 'aspect-[1.15/1]',
  },
  {
    slug: 'project-chat-session',
    title: 'Chat 多轮会话',
    group: 'Chat',
    href: '/docs/interface-guides/project-chat-session',
    image: '/api/reference-assets/project-chat-session.png',
    summary: '展示项目级对话、线程与结构化回复的交互式入口。',
    label: 'Chat Surface',
    note: '多轮线程与结果输出在同一项目上下文中展开。',
    objectPosition: '52% 28%',
    scale: 1.14,
    viewportClassName: 'aspect-[1.15/1]',
  },
  {
    slug: 'project-notebook-task-detail',
    title: 'Notebook 任务详情',
    group: 'Notebook',
    href: '/docs/interface-guides/project-notebook-task-detail',
    image: '/api/reference-assets/project-notebook-task-detail.png',
    summary: '承载任务消息、trace 与 artifacts 的核心执行页面。',
    label: 'Notebook Trace',
    note: '任务过程、状态与产物统一沉淀为可回看的执行记录。',
    objectPosition: '54% 30%',
    scale: 1.15,
    viewportClassName: 'aspect-[1.15/1]',
  },
  {
    slug: 'project-files',
    title: '文件库管理',
    group: 'Files',
    href: '/docs/interface-guides/project-files',
    image: '/api/reference-assets/project-files.png',
    summary: '项目文件库、本地挂载与上下文复用的关键页面。',
    label: 'Files Asset Layer',
    note: '本地挂载与平台文件库共同构成项目资产层。',
    objectPosition: '50% 36%',
    scale: 1.14,
    viewportClassName: 'aspect-[1.15/1]',
  },
  {
    slug: 'project-endpoints',
    title: 'Endpoint 管理',
    group: '治理与运营',
    href: '/docs/interface-guides/project-endpoints',
    image: '/api/reference-assets/project-endpoints.png',
    summary: '围绕 endpoint 资源建立统一治理主线的入口页面。',
    label: 'Governance',
    note: '统一管理项目可用模型资源与供应商接入。',
    objectPosition: '54% 30%',
    scale: 1.16,
    viewportClassName: 'aspect-[1.15/1]',
  },
  {
    slug: 'project-audit',
    title: '审计日志',
    group: '治理与运营',
    href: '/docs/interface-guides/project-audit',
    image: '/api/reference-assets/project-audit.png',
    summary: '用于查看配置变化、异常事件与追溯信息的审计页面。',
    label: 'Audit Evidence',
    note: '关键变更、异常与资源事件可集中追溯。',
    objectPosition: '55% 36%',
    scale: 1.13,
    viewportClassName: 'aspect-[1.15/1]',
  },
] as const;
