export const referencePages = [
  {
    slug: 'project-overview',
    title: '项目总览',
    group: '工作区与项目',
    href: '/docs/interface-guides/project-overview',
    image: '/api/reference-assets/project-overview.png',
    summary: '进入项目后的统一入口页，用于连接 Use 面与 Govern 面。',
  },
  {
    slug: 'project-chat-session',
    title: 'Chat 多轮会话',
    group: 'Chat',
    href: '/docs/interface-guides/project-chat-session',
    image: '/api/reference-assets/project-chat-session.png',
    summary: '展示项目级对话、线程与结构化回复的交互式入口。',
  },
  {
    slug: 'project-notebook-task-detail',
    title: 'Notebook 任务详情',
    group: 'Notebook',
    href: '/docs/interface-guides/project-notebook-task-detail',
    image: '/api/reference-assets/project-notebook-task-detail.png',
    summary: '承载任务消息、trace 与 artifacts 的核心执行证据页面。',
  },
  {
    slug: 'project-files',
    title: '文件库管理',
    group: 'Files',
    href: '/docs/interface-guides/project-files',
    image: '/api/reference-assets/project-files.png',
    summary: '项目文件库、本地挂载与上下文复用的关键页面。',
  },
  {
    slug: 'project-endpoints',
    title: 'Endpoint 管理',
    group: '治理与运营',
    href: '/docs/interface-guides/project-endpoints',
    image: '/api/reference-assets/project-endpoints.png',
    summary: '围绕 endpoint 资源建立统一治理主线的入口页面。',
  },
  {
    slug: 'project-audit',
    title: '审计日志',
    group: '治理与运营',
    href: '/docs/interface-guides/project-audit',
    image: '/api/reference-assets/project-audit.png',
    summary: '用于查看配置变化、异常事件与追溯证据的审计页面。',
  },
] as const;
