export const referencePages = [
  {
    slug: 'project-overview',
    title: '项目总览',
    group: '工作区与项目',
    href: '/docs/interface-guides/project-overview',
    preset: 'project-overview-guide',
    summary: '进入项目后的总览界面，用于连接聊天、任务、文件与治理能力。',
  },
  {
    slug: 'project-chat-session',
    title: 'Chat 多轮会话',
    group: 'Chat',
    href: '/docs/interface-guides/project-chat-session',
    preset: 'project-chat-session-guide',
    summary: '展示项目级对话、线程与结构化回复的交互式使用方式。',
  },
  {
    slug: 'project-notebook-task-detail',
    title: 'Notebook 任务详情',
    group: 'Notebook',
    href: '/docs/interface-guides/project-notebook-task-detail',
    preset: 'project-notebook-task-detail-guide',
    summary: '承载任务消息、trace 与 artifacts 的核心执行界面。',
  },
  {
    slug: 'project-files',
    title: '文件库管理',
    group: 'Files',
    href: '/docs/interface-guides/project-files',
    preset: 'project-files-guide',
    summary: '项目文件库、本地挂载与上下文复用的重要工作界面。',
  },
  {
    slug: 'project-endpoints',
    title: 'Endpoint 管理',
    group: '治理与运营',
    href: '/docs/interface-guides/project-endpoints',
    preset: 'project-endpoints-card',
    summary: '围绕 endpoint 资源建立统一治理主线的关键管理界面。',
  },
  {
    slug: 'project-audit',
    title: '审计日志',
    group: '治理与运营',
    href: '/docs/interface-guides/project-audit',
    preset: 'project-audit-card',
    summary: '用于查看配置变化、异常事件与追溯信息的审计界面。',
  },
  {
    slug: 'project-agents',
    title: '智能体列表',
    group: '智能体运行',
    href: '/docs/interface-guides/project-agents',
    preset: 'project-agents-topic',
    summary: '查看项目可用智能体、运行模式与交互方式的关键界面。',
  },
] as const;
