export type ScreenshotPreset = {
  key: string;
  src: string;
  alt: string;
  label?: string;
  note?: string;
  objectPosition?: string;
  scale?: number;
  viewportClassName?: string;
  recommendedUsage?: 'home' | 'guide' | 'capability' | 'topic';
};

const presets = [
  {
    key: 'project-overview-home',
    src: '/api/reference-assets/project-overview.png',
    alt: '项目总览',
    label: '项目入口',
    note: '在同一项目上下文中进入聊天、任务、文件与治理能力。',
    objectPosition: '52% 22%',
    scale: 1.24,
    viewportClassName: 'aspect-[1.08/1]',
    recommendedUsage: 'home',
  },
  {
    key: 'project-overview-guide',
    src: '/api/reference-assets/project-overview.png',
    alt: '项目总览',
    label: 'Project Surface',
    note: '统一进入聊天、任务、文件与治理。',
    objectPosition: '52% 22%',
    scale: 1.18,
    viewportClassName: 'aspect-[16/9]',
    recommendedUsage: 'guide',
  },
  {
    key: 'project-chat-session-home',
    src: '/api/reference-assets/project-chat-session.png',
    alt: 'Chat 多轮会话',
    label: 'Chat 会话',
    note: '多轮线程与结果输出保持在同一项目上下文中连续展开。',
    objectPosition: '52% 28%',
    scale: 1.15,
    viewportClassName: 'aspect-[1.2/1]',
    recommendedUsage: 'home',
  },
  {
    key: 'project-chat-session-guide',
    src: '/api/reference-assets/project-chat-session.png',
    alt: 'Chat 多轮会话',
    label: 'Chat Surface',
    note: '在项目上下文中组织多轮会话与结果输出。',
    objectPosition: '52% 28%',
    scale: 1.12,
    viewportClassName: 'aspect-[16/9]',
    recommendedUsage: 'guide',
  },
  {
    key: 'project-notebook-task-detail-home',
    src: '/api/reference-assets/project-notebook-task-detail.png',
    alt: 'Notebook 任务详情',
    label: 'Notebook 执行',
    note: '任务消息、执行状态与产物集中呈现，便于持续回看与复用。',
    objectPosition: '54% 29%',
    scale: 1.18,
    viewportClassName: 'aspect-[0.88/1]',
    recommendedUsage: 'home',
  },
  {
    key: 'project-notebook-task-detail-guide',
    src: '/api/reference-assets/project-notebook-task-detail.png',
    alt: 'Notebook 任务详情',
    label: 'Notebook Trace',
    note: '任务消息、执行状态与产物统一沉淀为长期记录。',
    objectPosition: '54% 30%',
    scale: 1.12,
    viewportClassName: 'aspect-[16/9]',
    recommendedUsage: 'guide',
  },
  {
    key: 'project-files-home',
    src: '/api/reference-assets/project-files.png',
    alt: '文件库管理',
    label: 'Files 资产层',
    note: '项目文件库、本地挂载与运行产物在同一上下文中协同。',
    objectPosition: '50% 36%',
    scale: 1.15,
    viewportClassName: 'aspect-[0.96/1]',
    recommendedUsage: 'home',
  },
  {
    key: 'project-files-guide',
    src: '/api/reference-assets/project-files.png',
    alt: '文件库管理',
    label: 'Files Asset Layer',
    note: '本地挂载与平台文件库共同形成项目资产层。',
    objectPosition: '50% 36%',
    scale: 1.12,
    viewportClassName: 'aspect-[16/9]',
    recommendedUsage: 'guide',
  },
  {
    key: 'project-endpoints-guide',
    src: '/api/reference-assets/project-endpoints.png',
    alt: 'Endpoint 管理',
    label: 'Endpoint Governance',
    note: '统一管理项目可用模型资源与供应商接入。',
    objectPosition: '54% 30%',
    scale: 1.12,
    viewportClassName: 'aspect-[16/9]',
    recommendedUsage: 'guide',
  },
  {
    key: 'project-endpoints-card',
    src: '/api/reference-assets/project-endpoints.png',
    alt: 'Endpoint 管理',
    label: 'Governance',
    note: '统一管理项目可用模型资源与供应商接入。',
    objectPosition: '54% 30%',
    scale: 1.16,
    viewportClassName: 'aspect-[1.15/1]',
    recommendedUsage: 'home',
  },
  {
    key: 'project-audit-guide',
    src: '/api/reference-assets/project-audit.png',
    alt: '审计日志',
    label: 'Audit Evidence',
    note: '集中查看关键变更、异常事件与资源操作。',
    objectPosition: '55% 36%',
    scale: 1.1,
    viewportClassName: 'aspect-[16/9]',
    recommendedUsage: 'guide',
  },
  {
    key: 'project-audit-card',
    src: '/api/reference-assets/project-audit.png',
    alt: '审计日志',
    label: 'Audit Evidence',
    note: '关键变更、异常与资源事件可集中追溯。',
    objectPosition: '55% 36%',
    scale: 1.13,
    viewportClassName: 'aspect-[1.15/1]',
    recommendedUsage: 'home',
  },
  {
    key: 'workspace-select-guide',
    src: '/api/reference-assets/workspace-select.png',
    alt: '工作区选择',
    label: 'Workspace Entry',
    note: '选择当前可访问的工作区，进入后续业务上下文。',
    objectPosition: '50% 48%',
    scale: 1.12,
    viewportClassName: 'aspect-[4/3]',
    recommendedUsage: 'guide',
  },
  {
    key: 'workspace-login-guide',
    src: '/api/reference-assets/workspace-login.png',
    alt: '工作区登录',
    label: 'Workspace Sign-In',
    note: '在工作区内完成统一登录，再进入项目与任务空间。',
    objectPosition: '50% 48%',
    scale: 1.12,
    viewportClassName: 'aspect-[4/3]',
    recommendedUsage: 'guide',
  },
  {
    key: 'workspace-projects-guide',
    src: '/api/reference-assets/workspace-projects.png',
    alt: '工作区项目列表',
    label: 'Workspace Projects',
    note: '在同一页面查看项目、搜索项目并创建新项目。',
    objectPosition: '52% 34%',
    scale: 1.1,
    viewportClassName: 'aspect-[16/9]',
    recommendedUsage: 'guide',
  },
  {
    key: 'dialog-project-create-guide',
    src: '/api/reference-assets/dialog-project-create.png',
    alt: '创建项目对话框',
    label: 'Create Project',
    note: '设置项目名称、可见性和加入策略，完成项目建立。',
    objectPosition: '74% 48%',
    scale: 1.1,
    viewportClassName: 'aspect-[5/4]',
    recommendedUsage: 'guide',
  },
  {
    key: 'project-notebook-list-guide',
    src: '/api/reference-assets/project-notebook-list.png',
    alt: 'Notebook 任务列表',
    label: 'Notebook Queue',
    note: '统一查看长期任务，并继续进入新的执行任务。',
    objectPosition: '54% 30%',
    scale: 1.12,
    viewportClassName: 'aspect-[16/9]',
    recommendedUsage: 'guide',
  },
  {
    key: 'dialog-notebook-task-create-guide',
    src: '/api/reference-assets/dialog-notebook-task-create.png',
    alt: '创建任务对话框',
    label: 'Create Task',
    note: '设定任务标题并选择执行智能体，开启长期任务。',
    objectPosition: '50% 50%',
    scale: 1.12,
    viewportClassName: 'aspect-[5/4]',
    recommendedUsage: 'guide',
  },
  {
    key: 'project-credentials-guide',
    src: '/api/reference-assets/project-credentials.png',
    alt: '凭据管理',
    label: 'Credentials',
    note: '统一管理项目可用凭据与轮换状态。',
    objectPosition: '54% 27%',
    scale: 1.1,
    viewportClassName: 'aspect-[16/9]',
    recommendedUsage: 'guide',
  },
  {
    key: 'project-members-guide',
    src: '/api/reference-assets/project-members.png',
    alt: '成员治理',
    label: 'Members',
    note: '统一管理成员、加入申请与访问状态。',
    objectPosition: '54% 32%',
    scale: 1.08,
    viewportClassName: 'aspect-[16/9]',
    recommendedUsage: 'guide',
  },
  {
    key: 'project-resource-policy-guide',
    src: '/api/reference-assets/project-resource-policy.png',
    alt: '资源策略',
    label: 'Policy Controls',
    note: '围绕端点访问规则、限流和费用约束统一治理。',
    objectPosition: '57% 36%',
    scale: 1.08,
    viewportClassName: 'aspect-[16/9]',
    recommendedUsage: 'guide',
  },
  {
    key: 'project-usage-guide',
    src: '/api/reference-assets/project-usage.png',
    alt: '用量与限额',
    label: 'Usage Limits',
    note: '查看剩余额度、支出与使用趋势。',
    objectPosition: '53% 32%',
    scale: 1.09,
    viewportClassName: 'aspect-[16/9]',
    recommendedUsage: 'guide',
  },
  {
    key: 'project-settings-guide',
    src: '/api/reference-assets/project-settings.png',
    alt: '项目设置',
    label: 'Project Settings',
    note: '维护项目基础信息、可见性与加入策略。',
    objectPosition: '56% 38%',
    scale: 1.08,
    viewportClassName: 'aspect-[16/9]',
    recommendedUsage: 'guide',
  },
  {
    key: 'project-agents-guide',
    src: '/api/reference-assets/project-agents.png',
    alt: '智能体列表',
    label: 'Agents',
    note: '集中管理可执行的项目级智能体与交互方式。',
    objectPosition: '53% 24%',
    scale: 1.12,
    viewportClassName: 'aspect-[16/9]',
    recommendedUsage: 'guide',
  },
  {
    key: 'dialog-agent-create-guide',
    src: '/api/reference-assets/dialog-agent-create.png',
    alt: '创建智能体对话框',
    label: 'Create Agent',
    note: '设置名称、交互方式与执行偏好，完成智能体接入。',
    objectPosition: '74% 48%',
    scale: 1.1,
    viewportClassName: 'aspect-[5/4]',
    recommendedUsage: 'guide',
  },
  {
    key: 'dialog-agent-connection-info-guide',
    src: '/api/reference-assets/dialog-agent-connection-info.png',
    alt: '智能体连接信息',
    label: 'Connection Info',
    note: '查看智能体连接地址与服务密钥信息。',
    objectPosition: '50% 52%',
    scale: 1.1,
    viewportClassName: 'aspect-[5/4]',
    recommendedUsage: 'guide',
  },
  {
    key: 'dialog-endpoint-create-guide',
    src: '/api/reference-assets/dialog-endpoint-create.png',
    alt: '创建端点对话框',
    label: 'Create Endpoint',
    note: '在引导模式和手动模式之间选择适合的接入方式。',
    objectPosition: '74% 48%',
    scale: 1.1,
    viewportClassName: 'aspect-[5/4]',
    recommendedUsage: 'guide',
  },
  {
    key: 'dialog-credential-create-guide',
    src: '/api/reference-assets/dialog-credential-create.png',
    alt: '创建凭据对话框',
    label: 'Create Credential',
    note: '在项目内新增 API 密钥并保持原始值不直接暴露。',
    objectPosition: '50% 52%',
    scale: 1.1,
    viewportClassName: 'aspect-[5/4]',
    recommendedUsage: 'guide',
  },
  {
    key: 'dialog-member-invite-guide',
    src: '/api/reference-assets/dialog-member-invite.png',
    alt: '邀请成员对话框',
    label: 'Invite Member',
    note: '通过邮箱与分组完成成员邀请，明确访问范围。',
    objectPosition: '50% 50%',
    scale: 1.08,
    viewportClassName: 'aspect-[5/4]',
    recommendedUsage: 'guide',
  },
  {
    key: 'dialog-file-library-create-guide',
    src: '/api/reference-assets/dialog-file-library-create.png',
    alt: '创建文件库对话框',
    label: 'Create Library',
    note: '为项目新增文件库，开始沉淀长期可复用的文件资产。',
    objectPosition: '50% 50%',
    scale: 1.08,
    viewportClassName: 'aspect-[5/4]',
    recommendedUsage: 'guide',
  },
  {
    key: 'dialog-file-library-mount-access-guide',
    src: '/api/reference-assets/dialog-file-library-mount-access.png',
    alt: '本地挂载信息',
    label: 'Mount Access',
    note: '查看本地挂载所需的路径、命令与访问方式。',
    objectPosition: '50% 52%',
    scale: 1.08,
    viewportClassName: 'aspect-[5/4]',
    recommendedUsage: 'guide',
  },
  {
    key: 'dialog-file-library-delete-denied-guide',
    src: '/api/reference-assets/dialog-file-library-delete-denied.png',
    alt: '文件库删除限制',
    label: 'Delete Guard',
    note: '当文件库仍被引用时，系统会明确提示删除限制。',
    objectPosition: '50% 52%',
    scale: 1.08,
    viewportClassName: 'aspect-[5/4]',
    recommendedUsage: 'guide',
  },
  {
    key: 'drawer-audit-detail-guide',
    src: '/api/reference-assets/drawer-audit-detail.png',
    alt: '审计事件详情',
    label: 'Audit Detail',
    note: '查看单次治理动作的详细字段、结果与 metadata。',
    objectPosition: '50% 50%',
    scale: 1.08,
    viewportClassName: 'aspect-[5/4]',
    recommendedUsage: 'guide',
  },
  {
    key: 'project-agents-topic',
    src: '/api/reference-assets/project-agents.png',
    alt: '智能体列表',
    label: 'Agent Registry',
    note: '把执行主体从零散脚本接入为项目内正式能力。',
    objectPosition: '53% 24%',
    scale: 1.16,
    viewportClassName: 'aspect-[1.15/1]',
    recommendedUsage: 'topic',
  },
] as const satisfies readonly ScreenshotPreset[];

const presetMap = new Map<string, ScreenshotPreset>(presets.map((preset) => [preset.key, preset]));

export function getScreenshotPreset(key: string): ScreenshotPreset {
  const preset = presetMap.get(key);
  if (!preset) {
    throw new Error(`Unknown screenshot preset: ${key}`);
  }

  return preset;
}

export const screenshotPresets = presets;
